import { Inter } from "next/font/google";
import { AuthContextProvider } from "@/app/context/AuthContext";
import { Providers } from "./providers";
import ToggleColorMode from "@/components/ToggleColorMode";
import MenuBar from "@/components/MenuBar";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <AuthContextProvider>
            <ToggleColorMode />
            {children}
            <MenuBar />
          </AuthContextProvider>
        </Providers>
      </body>
    </html>
  );
}
