import "./globals.css";
import { Inter } from "next/font/google";
import { AuthContextProvider } from "@/app/context/AuthContext";
import { ChakraProvider } from "@chakra-ui/react";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ChakraProvider>
          <AuthContextProvider>{children}</AuthContextProvider>
        </ChakraProvider>
      </body>
    </html>
  );
}
